use client"

import { useEffect } from 'react'

declare global {
  interface Window {
    openAdmin: () => void
    closeAdmin: () => void
    saveEdits: () => void
    resetEdits: () => void
    setLang: (v: string) => void
    loadEdits: () => void
  }
}

const pageHtml = `<div class="top"><span>FUNEL® Industrial Water Monitoring & Automation</span><span>WhatsApp: +86 15606523212 · Email: Claire@funel-sensor.com</span></div>
<nav class="nav"><a class="brand" href="#home"><img id="logoImg" src="/images/logo.png" alt="FUNEL logo"><span>FUNEL®</span></a><div class="menu"><a href="#products">Products</a><a href="#solutions">Solutions</a><a href="#automation">Automation</a><a href="#projects">Projects</a><a href="#about">About</a><a href="#contact">Contact</a></div><div class="nav-actions"><select class="lang" onchange="setLang(this.value)"><option>English</option><option>Español</option><option>Русский</option><option>العربية</option><option>한국어</option></select><button class="admin-btn" style="display:none" onclick="openAdmin()">Edit</button><a class="btn primary" href="https://sxfne1688.en.alibaba.com" target="_blank">Alibaba Store</a></div></nav>
<header id="home" class="hero"><div class="hero-text"><div class="eyebrow" data-edit="heroEyebrow">Engineered for water treatment projects</div><h1 data-edit="heroTitle">Industrial Water Monitoring & Process Automation Solutions</h1><p data-edit="heroDesc">FUNEL® supplies online water quality analyzers, digital sensors, PLC control cabinets and integrated monitoring systems for municipal water, wastewater, industrial process water and smart water projects.</p><div class="hero-actions"><a class="btn primary" href="#products">Explore Products</a><a class="btn ghost" href="#contact">Request Solution</a></div><div class="hero-stats"><div class="stat"><b>Online</b><br>Water Analyzers</div><div class="stat"><b>PLC</b><br>Automation Systems</div><div class="stat"><b>OEM</b><br>Project Support</div></div></div><div class="hero-media"><div class="hero-card"><div id="heroImage" class="hero-img"></div><div class="hero-card-body"><div class="mini"><b>Water Quality</b><br>pH, ORP, DO, turbidity, COD, ammonia, chlorine</div><div class="mini"><b>System Integration</b><br>Sampling, sensors, cabinet, data platform, remote monitoring</div></div></div></div></header>
<section id="products"><div class="section-head"><div class="tag">Product Center</div><h2>Online analyzers, sensors and monitoring systems</h2><p>Built for project-based water monitoring, system integration and industrial process control.</p></div><div class="grid4">
<div class="card product-card"><div id="pimg1" class="card-img" style="background-image:url('/images/online-analyzer.png')"></div><div class="card-body"><span class="pill">Water Quality Analyzer</span><h3 data-edit="p1Title">Online Water Quality Analyzers</h3><p data-edit="p1Desc">pH/ORP, dissolved oxygen, turbidity, suspended solids, conductivity, residual chlorine, COD, ammonia nitrogen and total phosphorus analyzers.</p><a class="link-slot" data-edit="p1Link" href="#contact">Add product detail link →</a></div></div>
<div class="card product-card"><div id="pimg2" class="card-img" style="background-image:url('/images/sensors-probes.png')"></div><div class="card-body"><span class="pill">Digital Sensors</span><h3 data-edit="p2Title">Industrial Sensors & Transmitters</h3><p data-edit="p2Desc">Digital probes, controllers, transmitters and accessories for online water analysis and industrial field installation.</p><a class="link-slot" data-edit="p2Link" href="#contact">Add product detail link →</a></div></div>
<div class="card product-card"><div id="pimg3" class="card-img" style="background-image:url('/images/monitoring-station.png')"></div><div class="card-body"><span class="pill">Integrated System</span><h3 data-edit="p3Title">Online Monitoring Stations</h3><p data-edit="p3Desc">Integrated sampling, pretreatment, online analysis, data acquisition and enclosure solutions for water quality monitoring stations.</p><a class="link-slot" data-edit="p3Link" href="#contact">Add product detail link →</a></div></div>

<div class="card product-card"><div id="pimg4" class="card-img" style="background-image:url('/images/muc-controller.png')"></div><div class="card-body"><span class="pill">Multiparameter Controller</span><h3 data-edit="p4Title">MUC Controllers & Transmitters</h3><p data-edit="p4Desc">Multi-parameter controllers and transmitters for pH, ORP, conductivity, turbidity, DO and integrated online monitoring.</p><a class="link-slot" data-edit="p4Link" href="#contact">Add product detail link →</a></div></div>
</div></section>
<section id="solutions" class="solutions"><div class="section-head"><div class="tag">Applications</div><h2>Solutions by water treatment scenario</h2><p>FUNEL® presents products by process and application, so engineers can quickly match instruments to monitoring points.</p></div><div class="grid3"><div class="solution"><h3>Municipal Water</h3><p>Intake water, sedimentation, filtration, disinfection and clear water monitoring.</p></div><div class="solution"><h3>Wastewater Treatment</h3><p>Inlet, aeration tank, sludge concentration, final effluent and discharge compliance.</p></div><div class="solution"><h3>Industrial Process Water</h3><p>Cooling water, boiler water, chemical dosing, recycling water and discharge monitoring.</p></div><div class="solution"><h3>Surface Water & Environment</h3><p>River, lake, groundwater and environmental station applications.</p></div><div class="solution"><h3>Aquaculture</h3><p>DO, pH, temperature, ammonia and water safety monitoring for farms.</p></div><div class="solution"><h3>Chemical & Manufacturing</h3><p>Online analysis and automation control for process safety and stable production.</p></div></div></section>
<section id="automation" class="dark"><div class="section-head"><div class="tag">Automation Integration</div><h2>From instrument to complete control system</h2><p>For overseas EPC contractors, integrators and distributors, FUNEL® can support complete monitoring architecture from field sensor to PLC/SCADA data layer.</p></div><div class="card" style="max-width:980px;margin:0 auto 32px;background:#fff;border:0"><div id="automationImage" class="card-img" style="height:430px;background-image:url('/images/plc-scada-system.png')"></div><div class="card-body"><span class="pill">PLC / SCADA</span><h3>Remote Monitoring Architecture</h3><p>System network, PLC/DCS control and SCADA screen display for water monitoring and automation projects.</p></div></div><div class="process"><div class="step"><span>1</span><h3>Sampling</h3><p>Sampling point design and pretreatment selection.</p></div><div class="step"><span>2</span><h3>Analysis</h3><p>Online analyzer, sensor and controller configuration.</p></div><div class="step"><span>3</span><h3>Cabinet</h3><p>PLC cabinet, power distribution and field wiring.</p></div><div class="step"><span>4</span><h3>Data</h3><p>RS485/4-20mA, gateway, cloud and SCADA integration.</p></div><div class="step"><span>5</span><h3>Service</h3><p>OEM support, commissioning guidance and spare parts.</p></div></div></section>
<section id="projects"><div class="section-head"><div class="tag">Project Experience</div><h2>Engineering-style project presentation</h2><p>Use this area to upload your real water plant, control cabinet, installation and commissioning photos.</p></div><div class="case"><div id="caseImage" class="card-img" style="background-image:url('/images/project-case.png')"></div><div class="case-list"><div class="case-item"><h3>Water Treatment Plant Monitoring</h3><p>Multi-parameter online monitoring for inlet, process and outlet water quality.</p></div><div class="case-item"><h3>Wastewater Automation Control</h3><p>PLC cabinet, field instruments and process data acquisition for stable operation.</p></div><div class="case-item"><h3>Industrial Discharge Monitoring</h3><p>Integrated station for COD, ammonia, pH, flow and compliance monitoring.</p></div></div></div></section>
<section id="about" class="about"><div class="split"><div><div class="tag">About FUNEL®</div><h2>Water analysis instruments with engineering capability</h2><p>FUNEL® focuses on industrial online water quality analysis, sensors, automation control and integrated monitoring systems. We serve water treatment companies, EPC contractors, system integrators, distributors and OEM partners.</p><p>Our website is structured around product families, process applications and project solutions, helping overseas customers understand both product supply and system integration ability.</p><div class="certs"><div class="cert">OEM / ODM</div><div class="cert">Technical Support</div><div class="cert">Project Integration</div><div class="cert">Global Inquiry</div></div></div><div class="card"><div id="aboutImage" class="card-img" style="height:430px;background-image:url('/images/factory-testing-packaging-shipment.png')"></div></div></div></section>
<section id="contact" class="contact"><div class="split"><div><div class="tag">Contact</div><h2>Send your project requirements</h2><p>Tell us your water type, monitoring parameters, measuring range, installation site and communication requirements. We will help select analyzers and system configuration.</p><div class="contact-box"><p><b>WhatsApp:</b> <a href="https://wa.me/8615606523212" target="_blank">+86 15606523212</a></p><p><b>Email:</b> <a href="mailto:Claire@funel-sensor.com">Claire@funel-sensor.com</a></p><p><b>Alibaba:</b> <a href="https://sxfne1688.en.alibaba.com" target="_blank">FUNEL Alibaba International Store</a></p><p><b>LinkedIn:</b> <a href="https://linkedin.com/in/claire-chen-1a6629399" target="_blank">Claire Chen</a></p></div></div><form class="form" onsubmit="event.preventDefault();location.href='mailto:Claire@funel-sensor.com?subject=FUNEL Inquiry&body=Please tell us your water type, parameters and project requirements.'"><input placeholder="Your name / company"><input placeholder="Email / WhatsApp"><input placeholder="Country / market"><textarea rows="7" placeholder="Project requirements: parameters, water type, range, quantity, application..."></textarea><button class="btn primary" type="submit">Send Inquiry</button></form></div></section>
<footer class="footer"><div><b>FUNEL®</b><br>Industrial Water Monitoring & Automation Solutions</div><div>© <span id="year"></span> FUNEL. All rights reserved.</div></footer>
<div class="float"><a href="https://wa.me/8615606523212" target="_blank">WhatsApp</a><a href="mailto:Claire@funel-sensor.com">Email</a><button style="display:none" onclick="openAdmin()">Edit Images</button></div>
<div id="adminModal" class="modal"><div class="panel"><h3>FUNEL Website Quick Editor</h3><div class="note">这是单文件 HTML 的“简易后台”：可以修改文字、图片 URL、产品链接，并保存在当前浏览器。正式上线后建议接入 WordPress / Webflow / Strapi CMS，后台可多人管理和上传图片。</div><div class="edit-grid" id="editorFields"></div><div style="display:flex;gap:10px;margin-top:18px;flex-wrap:wrap"><button class="btn primary" onclick="saveEdits()">Save Changes</button><button class="btn darkghost" onclick="resetEdits()">Reset</button><button class="btn darkghost" onclick="closeAdmin()">Close</button></div></div></div>
